const preguntas = [

"P4. ¿Con qué frecuencia utiliza motores de búsqueda como Google?",
"P5. Sabe cómo mejorar resultados de búsqueda avanzada.",
"P6. Sabe usar operadores AND, OR y NOT.",
"P7. Identifica fuentes confiables de información.",
"P8. Descarga y renombra documentos.",
"P9. Descarga bases de datos y genera estadísticas.",
"P10. Recopila datos mediante encuestas digitales.",
"P11. Utiliza IA para buscar información.",

"P12. Usa redes sociales para clientes.",
"P13. Redes sociales utilizadas.",
"P14. Usa correo electrónico para ventas.",
"P15. Usa videoconferencias como asistente.",
"P16. Usa videoconferencias para presentar información.",
"P17. Protege su privacidad en redes sociales.",
"P18. Evita spam en correos.",
"P19. Usa blogs o páginas personales.",

"P20. Usa Word o documentos digitales.",
"P21. Usa hojas de cálculo.",
"P22. Usa IA para presentaciones.",
"P23. Crea contenido en celular.",
"P24. Crea infografías.",
"P25. Edita videos.",
"P26. Edita audio.",
"P27. Conoce propiedad intelectual.",
"P28. Cita fuentes correctamente.",

"P29. Instala antivirus.",
"P30. Protege celular.",
"P31. Usa contraseñas seguras.",
"P32. Configura firewall.",
"P33. Revisa permisos de apps.",
"P34. Protege datos biométricos.",
"P35. Evita WiFi públicas para banca.",
"P36. Detecta correos sospechosos.",
"P37. Detecta fraudes.",
"P38. Reduce consumo energético digital.",

"P39. Soluciona problemas de cámara/micrófono.",
"P40. Busca soluciones en Internet.",
"P41. Usa traductores.",
"P42. Convierte ideas en acciones digitales.",
"P43. Mejora su aprendizaje digital.",
"P44. Usa plataformas educativas.",
"P45. Sigue aprendiendo tecnología.",
"P46. Usa herramientas para objetivos.",
"P47. Aprende nuevas apps.",
"P48. Ayuda a otros.",
"P49. Cree que la tecnología mejora su vida."

];